import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :planet, PlanetWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Planet.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# TODO Configure Before Going Live
config :planet, :paddle,
  sandbox: false,
  api_key: "3071a1d8b877b7325866d3ece8857018",
  bank_statement: "PADDLE.NET* RINKO"

# [Release] Check Runtime As Well
config :mnesia, dir: ~c"priv/mnesia"
